//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Giay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Giay()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }
        [Display(Name = "Mã Giày")]
        public int MaGiay { get; set; }
        [Display(Name = "Tên Giày")]
        [Required(ErrorMessage = "{0} không ???c ?? tr?ng")]
        public string TenGiay { get; set; }
        [Display(Name = "Giá Bán")]
        [Required(ErrorMessage = "{0} không ???c ?? tr?ng")]
        public Nullable<decimal> GiaBan { get; set; }
        
        
        public string AnhGiay { get; set; }
        
        [Required(ErrorMessage = "{0} không ???c ?? tr?ng")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString ="{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        
        [Required(ErrorMessage = "{0} không ???c ?? tr?ng")]
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<int> MaNSX { get; set; }
        public Nullable<int> MaLoai { get; set; }
        
        
        public Nullable<int> Moi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual Loai Loai { get; set; }
        
        
        public virtual NhaSanXuat NhaSanXuat { get; set; }
    }
}
