//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
        //display dùng ?? ??t l?i tên cho c?t
        [Display(Name ="Mã khách hàng")]
       
        public int MaKH { get; set; }
        [Display(Name ="H? tên")]
        [Required(ErrorMessage = "{0} không ???c ?? tr?ng")]
        public string HoTen { get; set; }
        [Display(Name = "Tài kho?n")]
        [Required(ErrorMessage = "{0} không ???c ?? tr?ng")]
        public string TaiKhoan { get; set; }
        [Display(Name = "M?t kh?u")]
        [Required(ErrorMessage = "{0} không ???c ?? tr?ng")]
        public string MatKhau { get; set; }
        [Required(ErrorMessage = "{0} không ???c ?? tr?ng")]
        public string Email { get; set; }
        [Display(Name = "??a ch?")]
        [Required(ErrorMessage = "{0} không ???c ?? tr?ng")]
        public string DiaChi { get; set; }
        [Display(Name = "S? ?i?n tho?i")]
        [Required(ErrorMessage = "{0} không ???c ?? tr?ng")]
        public string DienThoai { get; set; }
        [Display(Name = "Gi?i tính")]
        [Required(ErrorMessage = "{0} không ???c ?? tr?ng")]
        public string GioiTinh { get; set; }
        [Display(Name = "Ngày Sinh")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgaySinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}
